[package]
name = "puzzle"
version = "0.1.0"
authors = ["kmakeev <kmakeev@arbitr.ru>"]
edition = "2018"

[dependencies]
rand = "0.3.0"
rayon = "1.1"
csv = "1"
serde = "1"
serde_derive = "1"


[profile.dev]
debug = true
opt-level = 0

[profile.release]
opt-level = 3

